feat: Now also call restor script, and add diagnostic output

diff --git a/backend/entrypoint.d/main b/backend/entrypoint.d/main
--- a/backend/entrypoint.d/main
+++ b/backend/entrypoint.d/main
@@ -1,7 +1,13 @@
 #!/bin/sh
 
-set -e
+if ! ./entrypoint.d/restore-database; then
+	echo 'Database restore failed' >&2
+	exit 1
+fi
 
-./entrypoint.d/apply-migrations
+if ! ./entrypoint.d/apply-migrations; then
+	echo 'Migrations failed' >&2
+	exit 1
+fi
 
 exec "$@"
